// Scalable Vector CPU Project -- Additional configuration definitions
// Auto generated by configuration Tcl script
// Copyright (c) 2007 Jason Yu

// MACCHAINLENGTH * MAC_NUMMULT cannot be greater than NUMLANES
`define 	MACCHAINLENGTH 	2

`define 	LOAD_BYTE_ACCESS_ENABLED
`define 	STORE_BYTE_ACCESS_ENABLED
`define 	LOAD_HALFWORD_ACCESS_ENABLED
`define 	STORE_HALFWORD_ACCESS_ENABLED
`define 	LOAD_WORD_ACCESS_ENABLED
`define 	STORE_WORD_ACCESS_ENABLED
