#Please Run This Script Before Compiling
if {![info exists ::ppl_instance_name]} {set ::ppl_instance_name {}}
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_odt[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_odt[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_clk[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to ${::ppl_instance_name}mem_clk[0]
set_instance_assignment -name TREAT_BIDIR_AS_OUTPUT "ON" -to ${::ppl_instance_name}mem_clk[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_clk[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to ${::ppl_instance_name}mem_clk[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_clk_n[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to ${::ppl_instance_name}mem_clk_n[0]
set_instance_assignment -name TREAT_BIDIR_AS_OUTPUT "ON" -to ${::ppl_instance_name}mem_clk_n[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_clk_n[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITHOUT CALIBRATION" -to ${::ppl_instance_name}mem_clk_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_cs_n[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_cs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_cke[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_cke[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_addr[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_addr[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_ba[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_ba[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_ras_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_ras_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_cas_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_cas_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_we_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ${::ppl_instance_name}mem_we_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[0]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[1]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[2]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[2]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[3]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[3]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[4]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[4]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[5]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[5]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[6]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[6]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[7]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[7]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[8]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[8]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[9]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[9]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[10]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[10]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[11]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[11]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[12]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[12]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[13]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[13]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[14]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[14]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[15]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[15]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[16]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[16]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[17]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[17]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[18]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[18]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[19]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[19]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[20]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[20]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[21]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[21]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[22]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[22]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[23]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[23]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[24]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[24]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[25]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[25]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[26]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[26]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[27]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[27]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[28]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[28]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[29]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[29]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[30]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[30]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[31]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[31]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[32]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[32]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[32]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[33]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[33]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[33]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[34]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[34]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[34]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[35]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[35]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[35]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[36]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[36]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[36]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[37]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[37]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[37]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[38]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[38]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[38]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[39]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[39]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[39]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[40]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[40]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[40]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[41]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[41]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[41]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[42]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[42]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[42]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[43]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[43]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[43]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[44]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[44]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[44]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[45]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[45]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[45]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[46]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[46]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[46]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[47]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[47]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[47]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[48]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[48]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[48]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[49]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[49]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[49]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[50]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[50]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[50]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[51]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[51]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[51]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[52]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[52]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[52]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[53]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[53]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[53]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[54]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[54]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[54]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[55]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[55]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[55]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[56]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[56]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[56]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[57]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[57]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[57]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[58]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[58]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[58]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[59]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[59]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[59]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[60]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[60]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[60]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[61]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[61]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[61]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[62]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[62]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[62]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dq[63]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[63]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dq[63]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[0]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[1]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[2]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[2]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[2]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[3]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[3]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[3]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[4]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[4]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[4]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[5]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[5]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[5]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[6]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[6]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[6]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqs[7]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[7]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqs[7]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqs[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[0]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[1]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[2]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[2]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[2]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[3]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[3]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[3]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[4]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[4]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[4]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[5]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[5]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[5]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[6]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[6]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[6]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dqsn[7]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[7]
set_instance_assignment -name INPUT_TERMINATION "PARALLEL 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dqsn[7]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.8-V SSTL CLASS I" -to ${::ppl_instance_name}mem_dqsn[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[0]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[1]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[2]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[3]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[4]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[5]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[6]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ${::ppl_instance_name}mem_dm[7]
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 50 OHM WITH CALIBRATION" -to ${::ppl_instance_name}mem_dm[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[8]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[9]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[10]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[11]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[12]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[13]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[14]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[15]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[16]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[17]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[18]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[19]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[20]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[21]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[22]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[23]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[24]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[25]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[26]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[27]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[28]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[29]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[30]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[31]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[32]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[33]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[34]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[35]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[36]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[37]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[38]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[39]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[40]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[41]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[42]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[43]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[44]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[45]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[46]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[47]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[48]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[49]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[50]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[51]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[52]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[53]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[54]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[55]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[56]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[57]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[58]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[59]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[60]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[61]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[62]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dq[63]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqs[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dqsn[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1191024410" -to ${::ppl_instance_name}mem_dm[7]

if { [file exists altmemddr_phy_assign_dq_groups.tcl] } {
source altmemddr_phy_assign_dq_groups.tcl }
